UI/Areas/Admin/Controllers/BuscarController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="BuscarController.cs" company="Acheve Solutions">
//   Copyright (c) Hugo Biarge. Todos los derechos reservados.
// </copyright>
// <summary>
//   Defines the BuscarController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Acheve.UI.Areas.Admin.Controllers
{
    using System;
    using System.Web.Mvc;

    using Acheve.Data.Services.Contracts;
    using Acheve.UI.Areas.Admin.ViewModels;

    public class BuscarController : Controller
    {
        private readonly IJornadaQueries jornadaQueries;

        private readonly IUsuariosQueries usuariosQueries;

        public BuscarController(IJornadaQueries jornadaQueries, IUsuariosQueries usuariosQueries)
        {
            if (jornadaQueries == null)
            {
                throw new ArgumentNullException("jornadaQueries");
            }

            if (usuariosQueries == null)
            {
                throw new ArgumentNullException("usuariosQueries");
            }

            this.jornadaQueries = jornadaQueries;
            this.usuariosQueries = usuariosQueries;
        }

        public ActionResult Index()
        {
            var vm = new BuscarJornadasViewModel
            {
                Inicio = DateTime.Today.AddDays(-7),
                Fin = DateTime.Today,
                Usuarios = this.usuariosQueries.ObtenerUsuarios(),
                IsPost = false
            };

            return this.View(vm);
        }

        [HttpPost]
        public ActionResult Index(CriteriosBusquedaEntreFechasViewModel searchCriteria)
        {
            var vm = new BuscarJornadasViewModel
            {
                Inicio = searchCriteria.Inicio,
                Fin = searchCriteria.Fin,
                Usuario = searchCriteria.Usuario,
                Usuarios = this.usuariosQueries.ObtenerUsuarios(),
            };

            if (this.ModelState.IsValid)
            {
                var jornadas = this.jornadaQueries.ObtenerInformacionJornadasEntreFechas(
                    searchCriteria.Usuario, searchCriteria.Inicio, searchCriteria.Fin);

                vm.IsPost = true;
                vm.Usuario = searchCriteria.Usuario;
                vm.Jornadas = jornadas;
            }

            return this.View(vm);
        }
    }
}

UI/Controllers/InformeController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="InformeController.cs" company="Acheve Solutions">
//   Copyright (c) Hugo Biarge. Todos los derechos reservados.
// </copyright>
// <summary>
//   Defines the InformeController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Acheve.UI.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using Acheve.Data.Services.Contracts;
    using Acheve.UI.ViewModels;

    public class InformeController : Controller
    {
        private readonly IJornadaQueries jornadaQueries;

        public InformeController(IJornadaQueries jornadaQueries)
        {
            if (jornadaQueries == null)
            {
                throw new ArgumentNullException("jornadaQueries");
            }

            this.jornadaQueries = jornadaQueries;
        }

        public ViewResult Dia()
        {
            var vm = new InformeJornadaViewModel
            {
                Fecha = DateTime.Today.AddDays(-1),
                IsPost = false
            };

            return this.View(vm);
        }

        [HttpPost]
        public ViewResult Dia(CriteriosBusquedaFechaViewModel searchCriteria)
        {
            var vm = new InformeJornadaViewModel
            {
                Fecha = searchCriteria.Fecha,
            };

            if (this.ModelState.IsValid)
            {
                var jornada = this.jornadaQueries.ObtenerJornada(this.User.Identity.Name, searchCriteria.Fecha);
                var sumaPausas = jornada.Pausas.Aggregate(TimeSpan.Zero, (span, pausa) => span.Add(pausa.Duracion));

                vm.IsPost = true;
                vm.Jornada = jornada;
                vm.Total = jornada.Duracion;
                vm.SumaPausa = sumaPausas;
                vm.SumaTrabajo = jornada.Duracion.Subtract(sumaPausas);
            }

            return this.View(vm);
        }

        public ViewResult EntreFechas()
        {
            var vm = new InformeResumenEntreFechasViewModel
            {
                Inicio = DateTime.Today.AddDays(-7),
                Fin = DateTime.Today.AddDays(-1),
                IsPost = false
            };

            return this.View(vm);
        }

        [HttpPost]
        public ViewResult EntreFechas(CriteriosBusquedaEntreFechasViewModel searchCriteria)
        {
            var vm = new InformeResumenEntreFechasViewModel
            {
                Inicio = searchCriteria.Inicio,
                Fin = searchCriteria.Fin,
            };

            if (this.ModelState.IsValid)
            {
                var resumenJornadas = this.jornadaQueries.ObtenerResumenEntreFechas(
                        this.User.Identity.Name,
                        searchCriteria.Inicio,
                        searchCriteria.Fin).ToArray();

                vm.ResumenJornadas = resumenJornadas;
                vm.IsPost = true;
            }

            return this.View(vm);
        }
    }
}

UI/Controllers/SituacionController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SituacionController.cs" company="Acheve Solutions">
//   Copyright (c) Hugo Biarge. Todos los derechos reservados.
// </copyright>
// <summary>
//   Defines the SituacionController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Acheve.UI.Controllers
{
    using System;
    using System.Web.Mvc;

    using Acheve.Data.Services.Contracts;
    using Acheve.Domain.Services.Contracts;
    using Acheve.UI.Infrastructure;
    using Acheve.UI.ViewModels;

    public class SituacionController : Controller
    {
        private readonly IJornadaService jornadaService;

        private readonly IJornadaQueries jornadaQueries;

        public SituacionController(IJornadaService jornadaService, IJornadaQueries jornadaQueries)
        {
            if (jornadaService == null)
            {
                throw new ArgumentNullException("jornadaService");
            }

            if (jornadaQueries == null)
            {
                throw new ArgumentNullException("jornadaQueries");
            }

            this.jornadaService = jornadaService;
            this.jornadaQueries = jornadaQueries;
        }

        public ViewResult Actual()
        {
            var jornada = this.jornadaQueries.ObtenerUltimaJornada(this.User.Identity.Name);
            var vm = new JornadaViewModel
            {
                Jornada = jornada,
                Error = (string)this.TempData[Constantes.TempDataErrorKey]
            };

            return this.View(vm);
        }

        [ChildActionOnly]
        public PartialViewResult UltimasJornadas()
        {
            var ultimasJornadasRegistradas =
                this.jornadaQueries.ObtenerDiasUltimasJornadasRegistradas(this.User.Identity.Name);

            var vm = new JornadaNoIniciadaViewModel(ultimasJornadasRegistradas);

            return this.PartialView(vm);
        }

        [HttpPost]
        public RedirectToRouteResult IniciarJornada()
        {
            try
            {
                this.jornadaService.IniciarJornada(this.User.Identity.Name);
            }
            catch (InvalidOperationException e)
            {
                this.TempData[Constantes.TempDataErrorKey] = e.Message;
            }

            return this.RedirectToAction("Actual");
        }

        [HttpPost]
        public RedirectToRouteResult TerminarJornada()
        {
            try
            {
                this.jornadaService.TerminarJornada(this.User.Identity.Name);
            }
            catch (InvalidOperationException e)
            {
                this.TempData[Constantes.TempDataErrorKey] = e.Message;
            }

            return this.RedirectToAction("Actual");
        }

        [HttpPost]
        public RedirectToRouteResult IniciarPausa()
        {
            try
            {
                this.jornadaService.IniciarPausa(this.User.Identity.Name);
            }
            catch (InvalidOperationException e)
            {
                this.TempData[Constantes.TempDataErrorKey] = e.Message;
            }

            return this.RedirectToAction("Actual");
        }

        [HttpPost]
        public RedirectToRouteResult TerminarPausa()
        {
            try
            {
                this.jornadaService.TerminarPausa(this.User.Identity.Name);
            }
            catch (InvalidOperationException e)
            {
                this.TempData[Constantes.TempDataErrorKey] = e.Message;
            }

            return this.RedirectToAction("Actual");
        }
    }
}

UI/Views/Shared/NoAutorizado.cshtml
@{
    ViewBag.Title = "No Autorizado";
}

<style type="text/css">
    .title {
        color: #800000;
    }
</style>

<h2 class="title">No Autorizado</h2>
<p>Usted no está autorizado para acceder a esta página.</p>
<p>Póngase en contacto con el administrador del dominio si cree que debería poder acceder.</p>

UI/Views/Shared/_Layout.cshtml
@using Acheve.UI.App_Start
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Acheve - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <a class="brand" href="@Url.Action("Actual", "Situacion", new { area = string.Empty })">Acheve - Control de presencia</a>
            <div class="btn-group pull-right">
                <a class="btn btn-success dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-user icon-white"></i>&nbsp;@User.Identity.Name <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Salir", "LogOff", "Cuenta", new { area = string.Empty }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div id="menu" class="span2">
                <ul class="nav nav-list">
                    <li class="nav-header">Menu</li>
                    <li id="menSituacion"><a href="@Url.Action("Actual", "Situacion", new { area = string.Empty })">Situación actual</a></li>
                    <li id="menDiario"><a href="@Url.Action("Dia", "Informe", new { area = string.Empty })">Informe diario</a></li>
                    <li id="menFechas"><a href="@Url.Action("EntreFechas", "Informe", new { area = string.Empty })">Resumene entre fechas</a></li>
                </ul>
                @if (FluentSecurity.SecurityContext.Current.CurrentUserRoles().Contains(SecurityConfig.Roles.Jefe))
                {
                    <ul class="nav nav-list">
                        <li class="nav-header">Administración</li>
                        <li id="menAdminBuscar"><a href="@Url.Action("Index", "Buscar", new { area = "Admin" })">Mantenimiento</a></li>
                        <li id="menAdminDiario"><a href="@Url.Action("Dia", "Informe", new { area = "Admin" })">Informe diario</a></li>
                        <li id="menAdminFechas"><a href="@Url.Action("EntreFechas", "Informe", new { area = "Admin" })">Resumen entre fechas</a></li>
                    </ul>
                }
            </div>
            <div class="span10">
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/app/common")
    @RenderSection("scripts", required: false)
</body>
</html>