UI/Areas/Admin/Controllers/BuscarController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="BuscarController.cs" company="Acheve Solutions">
//   Copyright (c) Hugo Biarge. Todos los derechos reservados.
// </copyright>
// <summary>
//   Defines the BuscarController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Acheve.UI.Areas.Admin.Controllers
{
    using System;
    using System.Web.Mvc;

    using Acheve.Data.Services.Contracts;
    using Acheve.UI.Areas.Admin.ViewModels;

    public class BuscarController : Controller
    {
        private readonly IJornadaQueries jornadaQueries;

        private readonly IUsuariosQueries usuariosQueries;

        public BuscarController(IJornadaQueries jornadaQueries, IUsuariosQueries usuariosQueries)
        {
            if (jornadaQueries == null)
            {
                throw new ArgumentNullException("jornadaQueries");
            }

            if (usuariosQueries == null)
            {
                throw new ArgumentNullException("usuariosQueries");
            }

            this.jornadaQueries = jornadaQueries;
            this.usuariosQueries = usuariosQueries;
        }

        public ActionResult Index()
        {
            var vm = new BuscarJornadasViewModel
            {
                Inicio = DateTime.Today.AddDays(-7),
                Fin = DateTime.Today,
                Usuarios = this.usuariosQueries.ObtenerUsuarios(),
                IsPost = false
            };

            return this.View(vm);
        }

        [HttpPost]
        public ActionResult Index(CriteriosBusquedaEntreFechasViewModel searchCriteria)
        {
            var vm = new BuscarJornadasViewModel
            {
                Inicio = searchCriteria.Inicio,
                Fin = searchCriteria.Fin,
                Usuario = searchCriteria.Usuario,
                Usuarios = this.usuariosQueries.ObtenerUsuarios(),
            };

            if (this.ModelState.IsValid)
            {
                var jornadas = this.jornadaQueries.ObtenerInformacionJornadasEntreFechas(
                    searchCriteria.Usuario, searchCriteria.Inicio, searchCriteria.Fin);

                vm.IsPost = true;
                vm.Usuario = searchCriteria.Usuario;
                vm.Jornadas = jornadas;
            }

            return this.View(vm);
        }
    }
}

UI/Areas/Admin/Controllers/JornadaController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="JornadaController.cs" company="Acheve Solutions">
//   Copyright (c) Hugo Biarge. Todos los derechos reservados.
// </copyright>
// <summary>
//   Defines the JornadaController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Acheve.UI.Areas.Admin.Controllers
{
    using System;
    using System.Web.Mvc;

    using Acheve.Data.Services.Contracts;
    using Acheve.UI.Areas.Admin.ViewModels;
    using Acheve.UI.Infrastructure;
    using Acheve.UI.ViewModels;

    using CriteriosBusquedaFechaViewModel = Acheve.UI.Areas.Admin.ViewModels.CriteriosBusquedaFechaViewModel;
    using JornadaViewModel = Acheve.UI.Areas.Admin.ViewModels.JornadaViewModel;

    public class JornadaController : Controller
    {
        private readonly IJornadaQueries jornadaQueries;

        private readonly IJornadaCommands jornadaCommands;

        public JornadaController(IJornadaQueries jornadaQueries, IJornadaCommands jornadaCommands)
        {
            if (jornadaQueries == null)
            {
                throw new ArgumentNullException("jornadaQueries");
            }

            if (jornadaCommands == null)
            {
                throw new ArgumentNullException("jornadaCommands");
            }

            this.jornadaQueries = jornadaQueries;
            this.jornadaCommands = jornadaCommands;
        }

        public ActionResult Editar(CriteriosBusquedaFechaViewModel searchCriteria)
        {
            var jornada = this.jornadaQueries.ObtenerJornada(searchCriteria.Usuario, searchCriteria.Fecha);
            var vm = JornadaViewModel.FormJornada(jornada, searchCriteria.Usuario);

            return this.View(vm);
        }

        [HttpPost]
        public ActionResult Editar(JornadaEditViewModel jornadaViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Json(new { hasError = true, errors = this.ModelState.GetValidationErrors() });
            }

            try
            {
                var jornada = jornadaViewModel.ToJornada();
                this.jornadaCommands.ActualizarJornada(jornada, jornadaViewModel.Usuario);

                return this.Json(new { hasError = false, location = this.Url.Action("Index", "Buscar", new { usuario = jornadaViewModel.Usuario, fecha = jornadaViewModel.Dia.ToShortDateString() }) });
            }
            catch (Exception ex)
            {
                return this.Json(new { hasError = true, errors = new[] { new Error { ErrorMessage = ex.Message } } });
            }
        }

        public ActionResult Crear(CriteriosBusquedaFechaViewModel searchCriteria)
        {
            var vm = new JornadaViewModel
            {
                Usuario = searchCriteria.Usuario,
                Dia = searchCriteria.Fecha.ToShortDateString(),
                Inicio = searchCriteria.Fecha.ToShortDateString(),
                Fin = searchCriteria.Fecha.ToShortDateString()
            };

            return this.View(vm);
        }

        [HttpPost]
        public JsonResult Crear(JornadaEditViewModel jornadaViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Json(new { hasError = true, errors = this.ModelState.GetValidationErrors() });
            }

            try
            {
                var jornada = jornadaViewModel.ToJornada();
                this.jornadaCommands.CrearJornada(jornada, jornadaViewModel.Usuario);
                return this.Json(new { hasError = false, location = this.Url.Action("Index", "Buscar", new { usuario = jornadaViewModel.Usuario, fecha = jornadaViewModel.Dia.ToShortDateString() }) });
            }
            catch (Exception ex)
            {
                return this.Json(new { hasError = true, errors = new[] { new Error { ErrorMessage = ex.Message } } });
            }
        }

        [HttpPost]
        public JsonResult Eliminar(CriteriosBusquedaFechaViewModel searchCriteria)
        {
            var jornada = this.jornadaQueries.ObtenerJornada(searchCriteria.Usuario, searchCriteria.Fecha);

            if (jornada != null)
            {
                try
                {
                    this.jornadaCommands.EliminarJornada(jornada.Id);
                    return this.Json(new { hasError = false });
                }
                catch (Exception ex)
                {
                    return this.Json(new { hasError = true, errors = ex.Message });
                }
            }

            return this.Json(new { hasError = false });
        }
    }
}

UI/Controllers/InformeController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="InformeController.cs" company="Acheve Solutions">
//   Copyright (c) Hugo Biarge. Todos los derechos reservados.
// </copyright>
// <summary>
//   Defines the InformeController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Acheve.UI.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using Acheve.Data.Services.Contracts;
    using Acheve.UI.ViewModels;

    public class InformeController : Controller
    {
        private readonly IJornadaQueries jornadaQueries;

        public InformeController(IJornadaQueries jornadaQueries)
        {
            if (jornadaQueries == null)
            {
                throw new ArgumentNullException("jornadaQueries");
            }

            this.jornadaQueries = jornadaQueries;
        }

        public ViewResult Dia()
        {
            var vm = new InformeJornadaViewModel
            {
                Fecha = DateTime.Today.AddDays(-1),
                IsPost = false
            };

            return this.View(vm);
        }

        [HttpPost]
        public ViewResult Dia(CriteriosBusquedaFechaViewModel searchCriteria)
        {
            var vm = new InformeJornadaViewModel
            {
                Fecha = searchCriteria.Fecha,
            };

            if (this.ModelState.IsValid)
            {
                var jornada = this.jornadaQueries.ObtenerJornada(this.User.Identity.Name, searchCriteria.Fecha);
                var sumaPausas = jornada.Pausas.Aggregate(TimeSpan.Zero, (span, pausa) => span.Add(pausa.Duracion));

                vm.IsPost = true;
                vm.Jornada = jornada;
                vm.Total = jornada.Duracion;
                vm.SumaPausa = sumaPausas;
                vm.SumaTrabajo = jornada.Duracion.Subtract(sumaPausas);
            }

            return this.View(vm);
        }

        public ViewResult EntreFechas()
        {
            var vm = new InformeResumenEntreFechasViewModel
            {
                Inicio = DateTime.Today.AddDays(-7),
                Fin = DateTime.Today.AddDays(-1),
                IsPost = false
            };

            return this.View(vm);
        }

        [HttpPost]
        public ViewResult EntreFechas(CriteriosBusquedaEntreFechasViewModel searchCriteria)
        {
            var vm = new InformeResumenEntreFechasViewModel
            {
                Inicio = searchCriteria.Inicio,
                Fin = searchCriteria.Fin,
            };

            if (this.ModelState.IsValid)
            {
                var resumenJornadas = this.jornadaQueries.ObtenerResumenEntreFechas(
                        this.User.Identity.Name,
                        searchCriteria.Inicio,
                        searchCriteria.Fin).ToArray();

                vm.ResumenJornadas = resumenJornadas;
                vm.IsPost = true;
            }

            return this.View(vm);
        }
    }
}

UI/Areas/Admin/Views/Buscar/Index.cshtml
@model Acheve.UI.Areas.Admin.ViewModels.BuscarJornadasViewModel

@{
    ViewBag.Title = "Administración - Mantenimiento";
}

<ul class="breadcrumb">
    <li class="active">Administración<span class="divider">/</span></li>
    <li class="active">Mantenimiento</li>
</ul>

@using (Html.BeginForm("Index", "Buscar", new { area = "Admin" }, FormMethod.Post, new { @class = "form-inline" }))
{
    <fieldset>
        <legend>Seleccione el usuario y intervalo de fechas</legend>
        @Html.LabelFor(m => m.Usuario)
        @Html.DropDownListFor(m => m.Usuario, new SelectList(Model.Usuarios, Model.Usuario))
        @Html.LabelFor(m => m.Inicio)
        @Html.EditorFor(m => m.Inicio, "DateFrom")
        @Html.ValidationMessageFor(m => m.Inicio)
        @Html.LabelFor(m => m.Fin)
        @Html.EditorFor(m => m.Fin, "DateTo")
        <input id="btnBuscar" class="btn btn-primary" type="submit" value="Buscar" />
    </fieldset>
}

@if (Model.IsPost)
{
    <div class="row">
        <div class="span8">
            <table class="table table-striped table-hover table-condensed">
                <caption>Jornadas entre el @Model.Inicio.ToShortDateString() y el @Model.Fin.ToShortDateString() del usuario @Model.Usuario</caption>
                <thead>
                    <tr>
                        <th>Jornada</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var jornada in Model.Jornadas)
                    {
                        <tr>
                            <td><strong>@jornada.Dia.ToShortDateString()</strong></td>
                            @if (jornada.Existe)
                            {
                                <td>
                                    @using (Html.BeginForm("Dia", "Informe", new { usuario = Model.Usuario, fecha = jornada.Dia.ToShortDateString() }, FormMethod.Post, new { style = "display: inline;" }))
                                    {
                                        <input class="btn btn-primary" type="submit" value="Ver detalle" />
                                    }
                                </td>
                                <td>
                                    <a class="btn" href="@Url.Action("Editar", "Jornada", new { usuario = Model.Usuario, fecha = jornada.Dia.ToShortDateString() })">Editar</a>
                                </td>
                                <td>
                                    <button class="btn btn-primary disabled">Crear</button>
                                </td>
                                <td>
                                    <input class="btn btn-danger eliminar" type="submit" value="Eliminar" data-usuario="@Model.Usuario" data-fecha="@jornada.Dia.ToShortDateString()" />
                                </td>
                            }
                            else
                            {
                                <td>
                                    <button class="btn btn-primary disabled">Ver detalle</button></td>
                                <td>
                                    <button class="btn disabled">Editar</button></td>
                                <td>
                                    <a class="btn btn-primary" href="@Url.Action("Crear", "Jornada", new { usuario = Model.Usuario, fecha = jornada.Dia.ToShortDateString() })">Crear</a></td>
                                <td>
                                    <button class="btn btn-danger disabled">Eliminar</button></td>
                            }

                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="span2">
            @using (Html.BeginForm("EntreFechas", "Informe", new { usuario = Model.Usuario, inicio = Model.Inicio.ToShortDateString(), fin = Model.Fin.ToShortDateString() }))
            {
                <input class="btn btn-primary" type="submit" value="Ver resumen de horas" style="margin-top: 30px;" />
            }
        </div>
    </div>
}

@section scripts
{
    <script type="text/javascript">
        var my = my || {};
        my.data = my.data || {};

        my.marcarMenu('#menAdminBuscar');

        my.data.delete = function (json, callback) {
            my.data.ajaxPostJson(
                "@Url.Action("Eliminar", "Jornada")",
                json,
                callback);
        };

    </script>

    <script src="~/Scripts/App/index.js"></script>
}